version: '3.1'

services:

  db:
    image: mysql:8.0.24
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: micro_rabbit_banking_db
    ports:
      - 3306:3306