version: '3.1'

services:

  db:
    image: mysql:8.0.24
    restart: always
    container_name: micro_rabbit_db
    environment:
      MYSQL_ROOT_PASSWORD: test123
      MYSQL_DATABASE: micro_rabbit_banking_db
    ports:
      - 3306:3306

  rabbit_mq:
    image: rabbitmq:3-management-alpine
    container_name: micro_rabbit_mq
    ports:
      - 5672:5672
      - 15672:15672